// <auto-generated />
using Data_Access.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Access.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250317034010_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data_Access.Entities.Manufacturer", b =>
                {
                    b.Property<string>("ManufacturerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ManufacturerID");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CountryofOrigin")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("YearEstablished")
                        .HasColumnType("int");

                    b.HasKey("ManufacturerId")
                        .HasName("PK__Manufact__357E5CA18456C459");

                    b.ToTable("Manufacturer", (string)null);
                });

            modelBuilder.Entity("Data_Access.Entities.MedicineInformation", b =>
                {
                    b.Property<string>("MedicineId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MedicineID");

                    b.Property<string>("ActiveIngredients")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ExpirationDate")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ManufacturerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ManufacturerID");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("WarningsAndPrecautions")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("MedicineId")
                        .HasName("PK__Medicine__4F2128F0E8E0CD66");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("MedicineInformation", (string)null);
                });

            modelBuilder.Entity("Data_Access.Entities.StoreAccount", b =>
                {
                    b.Property<int>("StoreAccountId")
                        .HasColumnType("int")
                        .HasColumnName("StoreAccountID");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StoreAccountDescription")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("StoreAccountPassword")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.HasKey("StoreAccountId")
                        .HasName("PK__StoreAcc__42D52A6AF7A4E315");

                    b.HasIndex(new[] { "EmailAddress" }, "UQ__StoreAcc__49A1474007BB5BE7")
                        .IsUnique()
                        .HasFilter("[EmailAddress] IS NOT NULL");

                    b.ToTable("StoreAccount", (string)null);
                });

            modelBuilder.Entity("Data_Access.Entities.MedicineInformation", b =>
                {
                    b.HasOne("Data_Access.Entities.Manufacturer", "Manufacturer")
                        .WithMany("MedicineInformations")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__MedicineI__Manuf__3C69FB99");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Data_Access.Entities.Manufacturer", b =>
                {
                    b.Navigation("MedicineInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
